"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False


INSTALLED_APPS = [
    "django.contrib.contenttypes",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "authentication",
    "products",
    "orders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "drf_spectacular",
    "whitenoise.runserver_nostatic",
]

# Authentication
AUTH_USER_MODEL = "authentication.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_RENDERER_CLASSES": ("rest_framework.renderers.JSONRenderer",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "mediafiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# JWT Configuration
SIMPLE_JWT = {
    # Access token expira em 1 hora (curto por segurança)
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=1),
    # Refresh token expira em 7 dias (o user fica logado por 1 semana)
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    # Gera um novo refresh token a cada renovação (rotation)
    "ROTATE_REFRESH_TOKENS": True,
    # Coloca o refresh antigo na blacklist após rotation
    "BLACKLIST_AFTER_ROTATION": True,
    # Atualiza o last_login do user a cada chamada autenticada
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "TOKEN_OBTAIN_PAIR_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
}

GOOGLE_CLIENT_ID = config("GOOGLE_CLIENT_ID")

INFINITEPAY_HANDLE = config("INFINITEPAY_HANDLE", default="")

CORREIOS_API_BASE_URL = config(
    "CORREIOS_API_BASE_URL", default="https://api.correios.com.br"
)
CORREIOS_USERNAME = config("CORREIOS_USERNAME", default="")
CORREIOS_PASSWORD = config("CORREIOS_PASSWORD", default="")
CORREIOS_CARTAO_POSTAGEM = config("CORREIOS_CARTAO_POSTAGEM", default="")

CORREIOS_CODIGO_SERVICO = config("CORREIOS_CODIGO_SERVICO", default="03220")
CORREIOS_PESO_PADRAO_GRAMAS = config("CORREIOS_PESO_PADRAO_GRAMAS", default="300")
CORREIOS_REMETENTE_NOME = config("CORREIOS_REMETENTE_NOME", default="")
CORREIOS_REMETENTE_EMAIL = config("CORREIOS_REMETENTE_EMAIL", default="")
CORREIOS_REMETENTE_CPF_CNPJ = config("CORREIOS_REMETENTE_CPF_CNPJ", default="")
CORREIOS_REMETENTE_CEP = config("CORREIOS_REMETENTE_CEP", default="")
CORREIOS_REMETENTE_LOGRADOURO = config("CORREIOS_REMETENTE_LOGRADOURO", default="")
CORREIOS_REMETENTE_NUMERO = config("CORREIOS_REMETENTE_NUMERO", default="")
CORREIOS_REMETENTE_COMPLEMENTO = config("CORREIOS_REMETENTE_COMPLEMENTO", default="")
CORREIOS_REMETENTE_BAIRRO = config("CORREIOS_REMETENTE_BAIRRO", default="")
CORREIOS_REMETENTE_CIDADE = config("CORREIOS_REMETENTE_CIDADE", default="")
CORREIOS_REMETENTE_UF = config("CORREIOS_REMETENTE_UF", default="")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "authentication": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Shio API",
    "DESCRIPTION": (
        "API REST da plataforma Shio.\n\n"
        "## Autenticação\n\n"
        "Esta API usa **JWT Bearer Token**.\n\n"
        "1. Faça login em `POST /api/auth/google/` com o `id_token` do Google\n"
        "2. Copie o campo `access` da resposta\n"
        "3. Clique em **Authorize** (cadeado) e cole: `Bearer <access_token>`\n\n"
        "O access token expira em **1 hora**. Use `POST /api/auth/token/refresh/` para renovar."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Segurança — define o esquema JWT para o botão Authorize do Swagger UI
    "SECURITY": [{"BearerAuth": []}],
    "COMPONENTS": {
        "securitySchemes": {
            "BearerAuth": {
                "type": "http",
                "scheme": "bearer",
                "bearerFormat": "JWT",
                "description": "Token JWT. Formato: `Bearer <access_token>`",
            }
        }
    },
    # Ordenação e agrupamento por tags
    "SORT_OPERATIONS": True,
    "TAGS": [
        {
            "name": "Auth",
            "description": "Autenticação com Google OAuth 2.0 e gestão de sessões JWT.",
        },
        {
            "name": "Users",
            "description": "Dados do utilizador autenticado.",
        },
        {
            "name": "Categories",
            "description": "Gestão e listagem de categorias de produtos.",
        },
        {
            "name": "Drops",
            "description": "Gestão e listagem de campanhas de drop.",
        },
        {
            "name": "Products",
            "description": "Catálogo de produtos, variações e imagens.",
        },
        {
            "name": "Stock",
            "description": "Movimentações e histórico de estoque por variação.",
        },
    ],
    # Swagger UI — aparência e comportamento
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,  # Mantém o token entre reloads da página
        "displayOperationId": False,
        "defaultModelsExpandDepth": 2,
        "defaultModelExpandDepth": 2,
        "docExpansion": "list",  # Mostra os endpoints colapsados por default
        "filter": True,  # Barra de busca no topo
        "tryItOutEnabled": True,  # Botão "Try it out" activo por default
    },
    # Extensões úteis
    "ENUM_GENERATE_CHOICE_DESCRIPTION": True,
    "COMPONENT_SPLIT_REQUEST": True,  # Separa schemas de request e response
    "POSTPROCESSING_HOOKS": [
        "drf_spectacular.hooks.postprocess_schema_enums",
    ],
}
