# Generated by Django 5.0.4 on 2026-06-07 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "previous_status",
                    models.CharField(
                        choices=[
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("PAID", "Paid"),
                            ("PREPARING", "Preparing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("AWAITING_PAYMENT", "Awaiting Payment"),
                            ("PAID", "Paid"),
                            ("PREPARING", "Preparing"),
                            ("SHIPPED", "Shipped"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELED", "Canceled"),
                        ],
                        max_length=50,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "tracking_code",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.customerorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
