# Generated by Django 5.0.4 on 2026-05-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Data e hora de criação do registro.",
                        verbose_name="criado em",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Data e hora da última atualização do registro.",
                        verbose_name="atualizado em",
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="e-mail destinatário"),
                ),
                (
                    "template_name",
                    models.CharField(
                        choices=[
                            ("ORDER_PLACED", "Pedido criado"),
                            ("PAYMENT_CONFIRMED", "Pagamento confirmado"),
                            ("ORDER_SHIPPED", "Pedido enviado"),
                            ("PASSWORD_RESET", "Reset de senha"),
                            ("WELCOME", "Boas-vindas"),
                            ("LOW_STOCK_ALERT", "Alerta de estoque baixo"),
                        ],
                        max_length=30,
                        verbose_name="template",
                    ),
                ),
                ("subject", models.CharField(max_length=255, verbose_name="assunto")),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        help_text="Variáveis passadas ao template no momento do envio.",
                        verbose_name="contexto",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("SENT", "Enviado"),
                            ("FAILED", "Falhou"),
                            ("BOUNCED", "Bounce"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        default="",
                        help_text="sendgrid | console",
                        max_length=30,
                        verbose_name="provider",
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="ID da mensagem no provider",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, default="", verbose_name="mensagem de erro"),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True, verbose_name="enviado em")),
            ],
            options={
                "verbose_name": "log de e-mail",
                "verbose_name_plural": "logs de e-mail",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient_email", "template_name"],
                        name="notificatio_recipie_686bd8_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"], name="notificatio_status_6192b4_idx"
                    ),
                ],
            },
        ),
    ]
