# Generated by Django 5.0.4 on 2026-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='color',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
